export const CharactIntro = {
    Doraemon: {
        name: '哆啦A梦',
        realname: '哆啦A梦',
        birthday: '2112.9.3',
        constellation: '处女座',
        height: '129.3公分',
        weight: '129.3公斤',
        nature: '有时表现出正经，但不时会有脱线的表现',
        favorite: '铜锣烧',
        fear: '老鼠',
        dream: '帮助大雄成为一个成功的人',
        future: '',
        other1: '逃跑时速可达129.3公里',
        other2: '遇到老鼠时可跳到129.3公分',
        other3: '上围129.3公分',
        other4: '身体周长129.3公分',
        other5: '头的周长129.3公分',
        img: new URL('@/assets/character/Doraemon.png', import.meta.url).href,
    },
    Nobita: {
        name: '大雄',
        realname: '野比大雄',
        birthday: '8月7日',
        constellation: '狮子座',
        height: '140公分（长大后约176.9公分）',
        weight: '30公斤',
        nature: '心地善良，并乐于助人',
        favorite: '射击、翻花绳、睡觉、考试抱鸭蛋',
        fear: '青椒',
        dream: '成为一名优秀的科学家',
        future: '通过公职考试，成为环境保护局的自然调查员',
        other1: '入睡最短0.93秒，被说教最长2时15分59秒',
        other2: '小学五年三班（新版为月见台小学，漫画里是四年级）',
        other3: '在14年后的10月25日与静香订婚并结婚',
        other4: '',
        other5: '',
        img: new URL('@/assets/character/Nobita.png', import.meta.url).href,
    },
    Giant: {
        name: '胖虎',
        realname: '刚田武',
        birthday: '6月15日',
        constellation: '双子座',
        height: '145公分',
        weight: '60公斤',
        nature: '调皮，喜欢欺负人，但是疼爱家人，有责任感',
        favorite: '唱歌、做菜、欺负人',
        fear: '做家务',
        dream: '成为歌手',
        future: '成为职业超级市场老板',
        other1: '养了一只狗：酷哥',
        other2: '唱歌五音不全程度可以用噪音来形容',
        other3: '小学五年三班（新版为月见台小学，漫画里是四年级）',
        other4: '',
        other5: '',
        img: new URL('@/assets/character/Giant.png', import.meta.url).href,
    },
    Suneo: {
        name: '小夫',
        realname: '骨川小夫',
        birthday: '2月29日',
        constellation: '双鱼座',
        height: '135公分（长大后约173公分）',
        weight: '38公斤',
        nature: '高傲自大，但是能说会道，能很快乃至熟练使用哆啦道具',
        favorite: '炫耀、自恋、拍马屁',
        fear: '老师和学习',
        dream: '成为服装设计师',
        future: '继承了父亲的公司',
        other1: '养了两只暹罗猫：奇鲁奇鲁和安娜',
        other2: '唯一的烦恼是身高太矮小，还比大雄矮5cm，因此而强烈自卑',
        other3: '在早期还有尿床毛病，连睡觉的时候还要穿纸尿裤',
        other4: '小学五年三班（新版为月见台小学，漫画里是四年级）',
        other5: '',
        img: new URL('@/assets/character/Suneo.png', import.meta.url).href,
    },
    Shizuka: {
        name: '静香',
        realname: '源静香',
        birthday: '5月8日',
        constellation: '金牛座',
        height: '135公分（长大后约170公分）',
        weight: '38公斤',
        nature: '成绩优秀，头脑聪明，文静有礼貌',
        favorite: '洗澡、弹小提琴、烤地瓜',
        fear: '老师和学习',
        dream: '成为空姐、护士或外交官等',
        future: '未明确表示静香是否有实现梦想',
        other1: '养了两只宠物：白狗波吉、金丝雀小皮',
        other2: '小提琴技巧差却喜欢演奏给别人听，甚至比胖虎歌喉更具破坏力',
        other3: '小学五年三班（新版为月见台小学，漫画里是四年级）',
        other4: '在14年后的10月25日与大雄订婚并结婚',
        other5: '',
        img: new URL('@/assets/character/Shizuka.png', import.meta.url).href,
    },
    Dorami: {
        name: '哆啦美',
        realname: '哆啦美',
        birthday: '2114.12.2',
        constellation: '射手座',
        height: '100公分',
        weight: '91公斤',
        nature: '性格温和，但是很容易被惹而发脾气（多数是因哥哥）',
        favorite: '唱歌、蜜瓜面包',
        fear: '蟑螂',
        dream: '成为一名画家',
        future: '',
        other1: '特别为没有耳朵的兄长设计，因此用红色蝴蝶结代替耳朵',
        other2: '有时也会照顾大雄，以替代哥哥去检修时的空缺',
        other3: '多次担任助拳人，她的出现常造成大雄一行人的转机',
        other4: '',
        other5: '',
        img: new URL('@/assets/character/Dorami.png', import.meta.url).href,
    }
}