const CharactIntro = {
    Nobita: {
        1: {
            name: "大雄",
            realname: "野比大雄",
            birthday: "8月7日",
            height: "140公分",
            weight: "30公斤",
            nature: "心地善良，并乐于助人",
            favorite: "射击、翻花绳、睡觉、考试抱鸭蛋",
            fear: "青椒",
            img: new URL("@/assets/map/character/Nobita/3.png", import.meta.url).href,
        },
        2: {
            name: "哆啦A梦",
            birthday: "2112.9.3",
            height: "129.3公分",
            weight: "129.3公斤",
            nature: "有时表现出正经，但不时会有脱线的表现",
            favorite: "铜锣烧",
            fear: "老鼠",
            img: new URL("@/assets/map/character/Nobita/4.png", import.meta.url).href,
        },
        3: {
            name: "哆啦美",
            birthday: "2114.12.2",
            constellation: "射手座",
            height: "100公分",
            weight: "91公斤",
            nature: "性格温和，但是很容易被惹而发脾气（多数是因哥哥）",
            favorite: "唱歌、蜜瓜面包",
            fear: "蟑螂",
            img: new URL("@/assets/map/character/Nobita/5.png", import.meta.url).href,
        },
        4: {
            name: "大雄的妈妈",
            realname: "野比玉子",
            birthday: "2月16日",
            age: "38岁",
            nature: "一位勤劳的家庭主妇，个性相当保守，对于新产品及科技等毫无兴趣，常为家中赤字烦恼。",
            favorite: "插画",
            fear: "大雄考试得零分",
            img: new URL("@/assets/map/character/Nobita/2.png", import.meta.url).href,
        },
        5: {
            name: "大雄的爸爸",
            realname: "野比伸助",
            birthday: "1月24日",
            age: "36岁",
            nature: "朝九晚五的典型上班族，有抽烟的不良嗜好，对于音乐也甚喜好，曾经花钱买了很贵的音响。",
            favorite: "音乐",
            fear: "驾照考试",
            img: new URL("@/assets/map/character/Nobita/1.png", import.meta.url).href,
        }
    },
    Giant: {
        1: {
            name: "胖虎",
            realname: "刚田武",
            birthday: "6月15日",
            constellation: "双子座",
            height: "145公分",
            weight: "60公斤",
            nature: "调皮，喜欢欺负人，但是疼爱家人，有责任感",
            favorite: "唱歌、做菜、欺负人",
            fear: "做家务",
            img: new URL("@/assets/map/character/Giant/1.png", import.meta.url).href,
        },
        2: {
            name: "小朱",
            realname: "刚田小朱",
            birthday: "7月19日",
            age: "8-9岁",
            nature: "在故事初期较为凶悍粗鲁，后期个性变得较为文静多愁善感，她喜欢画漫画，并梦想成为一名漫画家。",
            favorite: "画漫画",
            img: new URL("@/assets/map/character/Giant/2.png", import.meta.url).href,
        },
        3: {
            name: "胖虎的妈妈",
            realname: "不详",
            birthday: "7月19日",
            age: "30-40岁",
            nature: "对胖虎实行的教育方式比较严厉，但对其他人包括大雄、静香、小夫都是和颜悦色，客客气气，没有任何脾气。",
            img: new URL("@/assets/map/character/Giant/3.png", import.meta.url).href,
        },
    }
}


/*

{

Giant: {
name: "胖虎",
realname: "刚田武",
birthday: "6月15日",
constellation: "双子座",
height: "145公分",
weight: "60公斤",
nature: "调皮，喜欢欺负人，但是疼爱家人，有责任感",
favorite: "唱歌、做菜、欺负人",
fear: "做家务",
dream: "成为歌手",
future: "成为职业超级市场老板",
other1: "养了一只狗：酷哥",
other2: "唱歌五音不全程度可以用噪音来形容",
other3: "小学五年三班（新版为月见台小学，漫画里是四年级）",
other4: "",
other5: "",
img: new URL("@/assets/character/Giant.png", import.meta.url).href,
},
Suneo: {
name: "小夫",
realname: "骨川小夫",
birthday: "2月29日",
constellation: "双鱼座",
height: "135公分（长大后约173公分）",
weight: "38公斤",
nature: "高傲自大，但是能说会道，能很快乃至熟练使用哆啦道具",
favorite: "炫耀、自恋、拍马屁",
fear: "老师和学习",
dream: "成为服装设计师",
future: "继承了父亲的公司",
other1: "养了两只暹罗猫：奇鲁奇鲁和安娜",
other2: "唯一的烦恼是身高太矮小，还比大雄矮5cm，因此而强烈自卑",
other3: "在早期还有尿床毛病，连睡觉的时候还要穿纸尿裤",
other4: "小学五年三班（新版为月见台小学，漫画里是四年级）",
other5: "",
img: new URL("@/assets/character/Suneo.png", import.meta.url).href,
},
Shizuka: {
name: "静香",
realname: "源静香",
birthday: "5月8日",
constellation: "金牛座",
height: "135公分（长大后约170公分）",
weight: "38公斤",
nature: "成绩优秀，头脑聪明，文静有礼貌",
favorite: "洗澡、弹小提琴、烤地瓜",
fear: "老师和学习",
dream: "成为空姐、护士或外交官等",
future: "未明确表示静香是否有实现梦想",
other1: "养了两只宠物：白狗波吉、金丝雀小皮",
other2: "小提琴技巧差却喜欢演奏给别人听，甚至比胖虎歌喉更具破坏力",
other3: "小学五年三班（新版为月见台小学，漫画里是四年级）",
other4: "在14年后的10月25日与大雄订婚并结婚",
other5: "",
img: new URL("@/assets/character/Shizuka.png", import.meta.url).href,
},
Dorami: {
name: "哆啦美",
realname: "哆啦美",
birthday: "2114.12.2",
constellation: "射手座",
height: "100公分",
weight: "91公斤",
nature: "性格温和，但是很容易被惹而发脾气（多数是因哥哥）",
favorite: "唱歌、蜜瓜面包",
fear: "蟑螂",
dream: "成为一名画家",
future: "",
other1: "特别为没有耳朵的兄长设计，因此用红色蝴蝶结代替耳朵",
other2: "有时也会照顾大雄，以替代哥哥去检修时的空缺",
other3: "多次担任助拳人，她的出现常造成大雄一行人的转机",
other4: "",
other5: "",
img: new URL("@/assets/character/Dorami.png", import.meta.url).href,
},
};*/

export default CharactIntro;
